module.exports = [
  `
  \`\`\`html
    <template>
      <vi-cell title="默认 default"></vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell title="显示边框" line></vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell
        title="带Icon" 
        iconName="setting">
      </vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell 
        title="只显示箭头" 
        iconName="setting" 
        link="{{true}}">
      </vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell 
        title="显示右侧描述信息" 
        iconName="setting" 
        link="{{true}}" 
        desc="我是描述...">
      </vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell 
        title="跳转到首页" 
        iconName="carame" 
        desc="linkType为:switchTab" 
        linkType="switchTab" 
        link="/pages/index/index">
      </vi-cell>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      <vi-cell-group title="带标题的cell-group">
        <vi-cell 
          title="带Icon" 
          iconName="setting">
        </vi-cell>
        <vi-cell 
          title="只显示箭头" 
          iconName="setting" 
          link="{{true}}">
        </vi-cell>
        <vi-cell 
          title="显示右侧描述信息" 
          iconName="setting" 
          link="{{true}}" 
          desc="我是描述...">
        </vi-cell>
        <vi-cell 
          title="跳转到首页" 
          desc="linkType为:navigateBack" 
          linkType="navigateBack" 
          iconName="carame" 
          link="/pages/index/index">
        </vi-cell>
      </vi-cell-group>
    </template>
  \`\`\`
  `,
  `
  \`\`\`html
    <template>
      
    </template>
  \`\`\`
  `,
]